ESTADO joga_primeira (ESTADO, int, int, int);
ESTADO joga_comb_maior_naipe (ESTADO, int, int, int);
ESTADO joga_comb_maior_valor (ESTADO, int, int, int);
ESTADO joga_straight_igual (ESTADO, int, int, int);
ESTADO joga_straight (ESTADO, int, int, int);
ESTADO joga_flush_igual_naipe(ESTADO, int, int, int);
ESTADO joga_flush(ESTADO, int, int, int);
ESTADO joga_4OfAKind (ESTADO, int, int, int);
ESTADO joga_full_house (ESTADO, int, int, int);
ESTADO joga_bot (ESTADO);