int indice(int, int);
long long int add_carta(long long int, int, int);
long long int rem_carta(long long int, int, int);
int carta_existe(long long int, int, int);
int conta_cartas(MAO);
int isFlush (MAO);
int da_valor_flush(MAO);
int isFullHouse(MAO);
int maior_trio_fullhouse(MAO);
int is4OfAKind(MAO);
int valor_4OfKind (MAO);
int isStraight (MAO);
int maior_valorStraight (MAO);
int da_maior_naipe_straight (MAO);
int isStraightFlush (MAO);
int ranking (MAO);
int combinacao_valida (MAO);
int compara_tamanho(MAO, MAO);
int da_valor (MAO);
int da_maior_naipe (MAO);
int combinacao_maior (MAO, MAO);
int posso_jogar (ESTADO);
int calcula_score (MAO);